### ISSUE TITLE
create_campaign Template is not iterable

### ISSUE THREAD

**Issue by afriapps** [ojii/django-mailchimp#18]
template = mailchimp.utils.get_connection().get_template_by_name('hexor_colab')
print dict(template)
# > 'Template' object is not iterable

This is whats happening in side the mailchimp.utils.get_connection().create_campaign() function.

**Comment by ojii** [comment]
This project will be maintained at https://github.com/piquadrat/django-mailchimp from now on, if this issue still exists, please report it again at the new location. Thank you
