### ISSUE TITLE
Chimpy requires simplejson

### ISSUE THREAD

**Issue by cpauya** [ojii/django-mailchimp#2]
I use Python 2.6 and it seems your version of chimpy still uses the unpatched version that depends on simplejson.  

I suggest you apply the patch at http://code.google.com/p/chimpy/issues/detail?id=7#c0 

For verbosity's sake here's the diff from the above patch:

```
+++ chimpy.py
@@ -1,7 +1,10 @@
 import urllib
 import urllib2
 import pprint
-import simplejson
+try:
+    import json
+except:
+    import simplejson as json
 from utils import transform_datetime
 from utils import flatten
 _debug = 1
@@ -49,7 +52,7 @@
         if _debug > 1:
             print __name__, "rpc call received", data

-        result = simplejson.loads(data)
+        result = json.loads(data)

         try:
             if 'error' in result:
```

**Comment by ojii** [comment]
thank's for reporting, I'm just going to use django's builtin simplejson
