### ISSUE TITLE
Adding content in the campaign using the template id

### ISSUE THREAD

**Issue by Meenakshiithape** [ojii/django-mailchimp#22]
Hello,
I pass  template id while creating the campaign to campaign_create( ) method. I want to dynamically add the content in that campaign according the template structure.
Can you please help me, how should i do this?

Thanks

**Comment by ojii** [comment]
Hi, please note that this repository is no longer actively maintained. Please head over to https://github.com/piquadrat/django-mailchimp thank you.

**Comment by Meenakshiithape** [comment]
Ok thanks
