### ISSUE TITLE
Trouble with package

### ISSUE THREAD

**Issue by dima-kov** [ojii/django-mailchimp#24]
After installing `manage.py runserver` cause error
`ImportError: cannot import name 'simplejson'`
It is because 

> django.utils.simplejson
> Since Django 1.5 drops support for Python 2.5, we can now rely on the json module being available in Python’s standard library, so we’ve removed our own copy of simplejson. You should now import json instead of django.utils.simplejson.
> 
> Unfortunately, this change might have unwanted side-effects, because of incompatibilities between versions of simplejson – see the backwards-incompatible changes section. If you rely on features added to simplejson after it became Python’s json, you should import simplejson explicitly.

Please, fix it.

**Comment by ojii** [comment]
I no longer maintain this, please try https://github.com/divio/django-mailchimp
