### ISSUE TITLE
'Overview' object has no attribute 'paginate'

### ISSUE THREAD

**Issue by benjamindell** [ojii/django-mailchimp#3]
I get this error when trying to access the main page. Looking at the views base class it doesnt seem to reference the paginate object at all.

Actual line that is erroring is django-mailchimp/mailchimp/views.py in handle_get, line 21

Also, i was wondering whether you had any plans to write up a simple explanation as to what you can  / cant do with django-mailchimp? I'm finding it a little difficult to navigate around the code to work out what i am able to do with it (and how).

**Comment by ojii** [comment]
To be perfectly honest, I do not intend to fully support this. I just thought I'd share the code since it does some cool stuff for us. However it is quite complicated to actually implement...

**Comment by benjamindell** [comment]
Hi Ojii,

No problem. Its a shame as i think this could be pretty powerful... but i completely understand :)

**Comment by ojii** [comment]
Really mailchimp is unfortunately too huge a beast to fully support.

**Comment by ojii** [comment]
This project will be maintained at https://github.com/piquadrat/django-mailchimp from now on, if this issue still exists, please report it again at the new location. Thank you
