### ISSUE TITLE
Install instructions are missing some steps

### ISSUE THREAD

**Issue by AnthonyBriggs** [ojii/django-mailchimp#7]
When I install mailchimp-django according to the instructions, I get the following error:

```
NoReverseMatch at /admin/mailchimp/campaign/

Reverse for 'mailchimp_overview' with arguments '()' and keyword arguments '{'page': 1}' not found.
```

Adding a line to my urls.py seems to fix the problem:

```
(r'^mailchimp/', include('mailchimp.urls')),
```

but is this the right path? The admin screen just has:

```
Log
Subject     Sent Date
Queue
Subject     Actions
No Campaigns in the Queue
```

instead of the campaigns (that I've set up on their web interface). Is there a way to refresh this page? How do I know it's installed correctly?

**Comment by golliher** [comment]
+1 on Anthony's issue.   Is his suggestion part of correctly installing django-mailchip?

**Comment by pegler** [comment]
I'm getting the same error after installing in django 1.2.5.

**Comment by ojii** [comment]
This project will be maintained at https://github.com/piquadrat/django-mailchimp from now on, if this issue still exists, please report it again at the new location. Thank you
